module.exports = {
    coldWord: [
        "Opt out",
        "No thanks",
        "No thanks.",
        "No thank you",
        "No thank you.",
        "Unsubscribe",
        "Stop",
        "No",
        "No, sorry",
        "Not interested",
        "Not interested.",
        "Nope",
    ],
    coldPhrase: [
        "Remove me",
        "take me off",
        "Stop messaging me",
        "Stop texting me",
        "Please remove us",
        "Please remove me",
        "Take me off your contact list.",
        "Take me off your contact list",
        "Take me off your list",
        "Please do not contact me again",
        "Do not contact me again",
    ],
    wrongInfo: ["Wrong number", "Wrong #"].join("|"),
};
