require("dotenv").config();

module.exports = [
    {
        client: "Summa Media",
        mailshakeApi: process.env.REACT_APP_SUMMA_MEDIA,
        airtableApi: process.env.AIRTABLE_API_KEY,
        numContacts: 5,
        airtableBase: "appPfAkOluijuGY1T",
        googleSheetId: "18HJ7UdA6BC4J89EQLinI9rsWfxO2EEzeF5hn3xXcct8",
    },
    {
        client: "Hornet",
        mailshakeApi: process.env.REACT_APP_HORNET,
        airtableApi: process.env.AIRTABLE_API_KEY,
        numContacts: 5,
        airtableBase: "appgkq8u5mAyVJ6HU",
        googleSheetId: "1JEGup18CLuqATWKPcJYF6jUBXWtQNBvSjxPBVZaPZLk",
    },
    {
        client: "Just Roofs And Gutters",
        mailshakeApi: process.env.REACT_APP_JUST_ROOFS_AND_GUTTERS,
        airtableApi: process.env.AIRTABLE_API_KEY,
        numContacts: 15,
        airtableBase: "appEEsvEbsFQR2auL",
        googleSheetId: "1o8D2RTQZuqm1H1X2wLMTYa0RobrMa5wnQznp3fVYgLo",
    },
    {
        client: "Titan",
        mailshakeApi: process.env.REACT_APP_TITAN,
        airtableApi: process.env.AIRTABLE_API_KEY,
        numContacts: 5,
        airtableBase: "appqOh4lpuC1DTZS6",
        googleSheetId: "123",
    },
    {
        client: "Integrity",
        mailshakeApi: process.env.REACT_APP_INTEGRITY,
        airtableApi: process.env.AIRTABLE_API_KEY,
        numContacts: 5,
        airtableBase: "appLVlpoe7RYAQfm9",
        googleSheetId: "1RBZyhTr0D7FusS9U99s9aGjnpo_45Wafm51ctRMP7Mc",
    },
    {
        client: "Farha",
        mailshakeApi: process.env.REACT_APP_FARHA,
        airtableApi: process.env.AIRTABLE_API_KEY,
        numContacts: 5,
        airtableBase: "appAJd8DNpOfsXN53",
        googleSheetId: "123",
    },
    {
        client: "Rooftek",
        mailshakeApi: process.env.REACT_APP_ROOFTEK,
        airtableApi: process.env.AIRTABLE_API_KEY,
        numContacts: 5,
        airtableBase: "app115xQzw1jhn5U8",
        googleSheetId: "1a_ngOoI8jB0iL9zN57z-v2PA4ZbhYhS-LZeqRnTDXbw",
    },
    {
        client: "Custom Installations",
        mailshakeApi: process.env.REACT_APP_CUSTOM_INSTALLATIONS,
        airtableApi: process.env.AIRTABLE_API_KEY,
        numContacts: 5,
        airtableBase: "appbVNvX9lyC1qjOP",
        googleSheetId: "123",
    },
];
